time = ('Flamengo','Santos','Palmeiras','Grêmio','Athelico-PR','São Paulo','Internacional','Corinthians','Fortaleza','Goiás','Bahia','Vasco','Atlético','Fluminense','Botafogo','Ceará','Cruzeiro','Csa','Chapecoense','Avaí')
print(f'Lista de times do brasileirão {time}')
print('='*248)
print(f'Os 5 primeiros são {time[:6]}')
print('='*248)
print(f'Os 4 ultimos são {time[16:]}')
print('='*248)
print(f'Times em ordem alfábetica {sorted(time)}')
print('='*248)
print(f'A {time[18]} está na posição 18.')